apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    navya.solutions.service: sample-app-db
  name: sample-app-db
spec:
  serviceName: "sample-app-db"
  replicas: 1
  selector:
    matchLabels:
      navya.solutions.service: sample-app-db
  template:
    metadata:
      labels:
        navya.solutions.service: sample-app-db
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_PASSWORD
              value: st001_op
          image: navyasolutions/workshop-postgresql:1.0
          imagePullPolicy: ""
          name: workshop-postgresql
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: sample-app-storage
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: sample-app-storage
          persistentVolumeClaim:
            claimName: sample-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    navya.solutions.service: sample-app-db
  name: sample-app-db
spec:
  ports:
    - name: "DB"
      port: 5432
      targetPort: 5432
  selector:
    navya.solutions.service: sample-app-db
