version: "3.8"
services:
  graphql-gateway:
    container_name: graphql-gateway
    image: navyasolutions/graphql-gateway:latest
    networks:
      - ns-network
    environment:
      app-config.grpcServiceHost: "${GRPC_SERVICE_HOST}"
      app-config.grpcServicePort: "${GRPC_SERVICE_PORT}"
    ports:
      - 8086:8086
    depends_on:
      - grpc-service

  rest-gateway:
    container_name: rest-gateway
    image: navyasolutions/rest-gateway:latest
    networks:
      - ns-network
    ports:
      - 8087:8087

  grpc-service:
    container_name: grpc-service
    image: navyasolutions/grpc-service:latest
    networks:
      - ns-network
    volumes:
      - ~/docker/grpc-service/:/app
    ports:
      - 6566:6566
    environment:
      SPRING_DATASOURCE_URL: "${GRPC_SERVICE_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${GRPC_SERVICE_DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${GRPC_SERVICE_DB_PASSWORD}"
    depends_on:
      - postgres


  postgres:
    container_name: workshop-postgresql
    image: navyasolutions/workshop-postgresql:1.0
    volumes:
      - ns-volume:/var/lib/postgresql/data
    networks:
      - ns-network
    restart: always
    environment:
      POSTGRES_PASSWORD: st001_op
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  ns-network:

volumes:
  ns-volume:
