version: '3.7'
services:
  storage:
    image: ghcr.io/openzipkin/zipkin-elasticsearch7:${TAG:-latest}
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    # Uncomment to expose the storage port for testing
    ports:
      - 9200:9200
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch:9200
      # Uncomment to see requests to and from elasticsearch
      - ES_HTTP_LOGGING=BODY
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    command: --logging.level.zipkin2=DEBUG
    depends_on:
      - storage

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  elasticsearch-data:
    driver: local
