global:
  scrape_interval: 10s # How frequently to scrape targets by default

scrape_configs:
  - job_name: graphql-gateway
    metrics_path: '/actuator/prometheus'  # The HTTP resource path on which to fetch metrics from targets.
    scrape_interval: 5s # How frequently to scrape targets from this job.
    static_configs:
      - targets: ['192.168.1.156:8086']
  - job_name: grpc-service # The job name is assigned to scraped metrics by default.
    metrics_path: '/actuator/prometheus'  # The HTTP resource path on which to fetch metrics from targets.
    scrape_interval: 5s # How frequently to scrape targets from this job.
    static_configs: # A static_config allows specifying a list of targets and a common label set for them
      - targets: ['192.168.1.156:8088']


#Note: Use machine IP as target when run prometheus inside docker and app on machine